### ISSUE TITLE
Streamline RRT and RRT*

### ISSUE THREAD

**Issue by hardesh** [ERC-BPGC/gennav#1]

**Comment by hardesh** [comment]
Added working RRT in #4

**Comment by hardesh** [comment]
added RRT* in #7

**Comment by threewisemonkeys-as** [comment]
For anyone taking this up -
1. There are currently two implementations. These need to merged into one
2. The final implementation should follow `core.py`

**Comment by hardesh** [comment]
In the `rrtstar.py` you'll have to add `collision_check_function` which uses shapely. If you directly do this, then you'll get a lot of errors and then you'll have to solve them one by one.

Instead, whoever is taking the task, implement the algorithm from scratch, while taking shapely into account.
