### ISSUE TITLE
Test PRM on trotbot

### ISSUE THREAD

**Issue by threewisemonkeys-as** [ERC-BPGC/gennav#39]
Good issue for those who want to get famililar with ROS also

**Comment by SuhrudhSarathy** [comment]
To simulate trotbot try the omnibase robot in gazebo simulator. Refer ERC's repository https://github.com/ERC-BPGC/omnibase

**Comment by threewisemonkeys-as** [comment]
Closing since we are working on [gennav_ros](https://github.com/ERC-BPGC/gennav_ros) for this
